# ==========================
# ===  General settings  ===
# ==========================

set -g default-terminal "screen-256color"
set -g history-limit 999999999
set -g buffer-limit 1
set -sg escape-time 0
set -g display-time 1500
set -g remain-on-exit off
set -g repeat-time 300
setw -g allow-rename off
setw -g automatic-rename off
setw -g aggressive-resize on

# Set parent terminal title to reflect current window in tmux session 
set -g set-titles on
set -g set-titles-string "#S:#W"

# Start index of window/pane with 1, because we're humans, not computers
set -g base-index 1
setw -g pane-base-index 1

# =====================================
# ===           Theme               ===
# =====================================

# black
color_black_bg=colour0       #1d1f21
color_black_fg=colour8       #969896

# red
color_red_bg=colour1       #cc342b
color_red_fg=colour9       #cc342b

# green
color_green_bg=colour2       #198844
color_green_fg=colour10      #198844

# yellow
color_yallow_bf=colour3       #fba922
color_yallow_fg=colour11      #fba922

# blue
color_blue_bg=colour4       #3971ed
color_blue_fg=colour12      #3971ed

# magenta
color_magenta_bg=colour5       #a36ac7
color_magenta_fg=colour13      #a36ac7

# cyan
color_cyan_bg=colour6       #3971ed
color_cyan_fg=colour14      #3971ed

# white
color_white_bg=colour7       #c5c8c6
color_white_fg=colour15      #ffffff

# =====================================
# ===    Appearence and status bar  ===
# ======================================

## window segments in status line
set -g window-status-separator "|"
separator_powerline_left="["
separator_powerline_right="]"
setw -g window-status-format " #I:#W "

setw -g window-status-current-format "$separator_powerline_left#I:#W$separator_powerline_right"


setw -g window-status-current-style "fg=$color_green_fg,bg=$color_black_bg"

## when window has monitoring notification
setw -g window-status-activity-style "fg=$color_red_fg,bg=$color_red_bg"
#
## outline for active pane
set -g pane-border-style "fg=$color_black_bg"
set -g pane-active-border-style "fg=$color_green_fg"

# general status bar settings
set -g status on
set -g status-interval 1
set -g status-position bottom
set -g status-justify left
set -g status-right-length 100
set -g status-left-length 200


# define widgets we're going to use in status bar
# note, that this is not the complete list, some of them are loaded from plugins
wg_date="%h %d %H:%M"
wg_user_host="#(whoami)@#H"
wg_is_zoomed="#{?window_zoomed_flag,[Z],}"
## TODO: highlighted for nested local session as well
wg_is_keys_off="#([ $(tmux show-option -qv key-table) = 'off' ] && echo 'OFF')"
#
wg_session="#[fg=$color_yallow_fg] #S #[default]"
set -g status-left "$wg_session"
set -g status-right "$wg_is_keys_off $wg_is_zoomed | $wg_user_host | $wg_date"

